stages:
  - publish
  - update
  - code-quality
  - validate
  - static-analysis
  - deploy_dev
  - destroy_dev

variables:
  # Terraform Variables
  TERRAFORM_VERSION: "1.11.4"
  TF_ROOT: "${CI_PROJECT_DIR}/terraform"  # The relative path to the root directory of the Terraform project
  TF_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}"
  TF_USERNAME: "gitlab-ci-token"
  TF_PASSWORD: "${CI_JOB_TOKEN}"
  TFSEC_VERSION: "latest"
  # Schedule Creation Variables
  BASH_VERSION: "latest"
  # Gitlab Variables
  GITLAB_PROJECTS_URL_PREFIX: "https://cicd.skyway.porsche.com/api/v4/projects"
  # BISE Variables
  SECRETSCANNER_PIPELINE_BEHAVIOR: "fail"

image:
  name: hashicorp/terraform:${TERRAFORM_VERSION}
  # Entrypoint is also needed as image by default sets `terraform` binary as an entrypoint.
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

.setup-variables: &setup-variables |
  # Set variables for the HTTP backend to default to TF_* values
  export TF_HTTP_ADDRESS="${TF_HTTP_ADDRESS:-${TF_ADDRESS}}"
  export TF_HTTP_LOCK_ADDRESS="${TF_HTTP_LOCK_ADDRESS:-${TF_ADDRESS}/lock}"
  export TF_HTTP_LOCK_METHOD="${TF_HTTP_LOCK_METHOD:-POST}"
  export TF_HTTP_UNLOCK_ADDRESS="${TF_HTTP_UNLOCK_ADDRESS:-${TF_ADDRESS}/lock}"
  export TF_HTTP_UNLOCK_METHOD="${TF_HTTP_UNLOCK_METHOD:-DELETE}"
  export TF_HTTP_USERNAME="${TF_HTTP_USERNAME:-${TF_USERNAME}}"
  export TF_HTTP_PASSWORD="${TF_HTTP_PASSWORD:-${TF_PASSWORD}}"
  export TF_HTTP_RETRY_WAIT_MIN="${TF_HTTP_RETRY_WAIT_MIN:-5}"
  # Expose Gitlab specific variables to terraform since no -tf-var is available
  # Usable in the .tf file as variable "CI_JOB_ID" { type = string } etc
  export TF_VAR_CI_JOB_ID="${TF_VAR_CI_JOB_ID:-${CI_JOB_ID}}"
  export TF_VAR_CI_COMMIT_SHA="${TF_VAR_CI_COMMIT_SHA:-${CI_COMMIT_SHA}}"
  export TF_VAR_CI_JOB_STAGE="${TF_VAR_CI_JOB_STAGE:-${CI_JOB_STAGE}}"
  export TF_VAR_CI_PROJECT_ID="${TF_VAR_CI_PROJECT_ID:-${CI_PROJECT_ID}}"
  export TF_VAR_CI_PROJECT_NAME="${TF_VAR_CI_PROJECT_NAME:-${CI_PROJECT_NAME}}"
  export TF_VAR_CI_PROJECT_NAMESPACE="${TF_VAR_CI_PROJECT_NAMESPACE:-${CI_PROJECT_NAMESPACE}}"
  export TF_VAR_CI_PROJECT_PATH="${TF_VAR_CI_PROJECT_PATH:-${CI_PROJECT_PATH}}"
  export TF_VAR_CI_PROJECT_URL="${TF_VAR_CI_PROJECT_URL:-${CI_PROJECT_URL}}"
  export TF_VAR_CI_COMMIT_AUTHOR="${TF_VAR_CI_COMMIT_AUTHOR:-${CI_COMMIT_AUTHOR}}"
  # Setting up variables to be passed into terraform plan
  export TF_VARS="${TF_VARS} -var env_id=${ENV_ID}"

.terraform-init: &terraform-init |
  terraform --version
  echo "Initializing backend config."
  echo "Setting backend to $PIPELINE_TYPE"
  cd $TF_ROOT && terraform init

.install-requirements: &install-requirements |
  apk update
  apk upgrade --available
  apk add --no-cache aws-cli
  apk add --no-cache jq
  apk add --no-cache npm
  aws --version
  jq --version

.git-config: &git-config |
  git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/".insteadOf "ssh://git@${CI_SERVER_HOST}/"

.aws-oidc-login: &aws-oidc-login |
  echo "Variable AWS_OIDC_IAM_ROLE_ARN found and has a value, setting AWS credentials"
  mkdir -p ~/.aws
  echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
  echo -e "[default]\nrole_arn=${AWS_OIDC_IAM_ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config
  export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
    $(aws sts assume-role-with-web-identity \
    --role-arn ${AWS_OIDC_IAM_ROLE_ARN} \
    --role-session-name "Skyway-GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}" \
    --web-identity-token ${GITLAB_OIDC_TOKEN} \
    --duration-seconds 3600 \
    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
    --output text))
  aws sts get-caller-identity

####################
# code-quality stage jobs
####################

.terraform:fmt:
  stage: code-quality
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://cicd.skyway.porsche.com
  before_script:
    - *install-requirements
    - *aws-oidc-login
  script:
    - terraform --version
    - FMT=$(find . -name '*.tf' -or -name '*.tfvars' | xargs -I{} terraform fmt -write=false {})
    - if [ ! -z "${FMT}" ]; then echo -e "The following files are formatted incorrectly\n${FMT}" && exit 1; else echo "Terraform formatting looks good" && exit 0; fi

####################
# validate stage jobs
####################

.terraform:validate:
  stage: validate
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://cicd.skyway.porsche.com
  before_script:
    - *install-requirements
    - *aws-oidc-login
    - *git-config
    - *setup-variables
    - *terraform-init
  script:
    - terraform validate

####################
# plan stage jobs
####################

.terraform:plan:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://cicd.skyway.porsche.com
  before_script:
    - *install-requirements
    - *aws-oidc-login
    - *git-config
    - *setup-variables
    - echo "Terraform variables set to ${TF_VARS}"
    - *terraform-init
  script:
    - terraform plan -out="$CI_PROJECT_DIR/terraform-plan-${TF_STATE_NAME}.tfplan" ${TF_VARS}
    - terraform show -json $CI_PROJECT_DIR/terraform-plan-${TF_STATE_NAME}.tfplan > $CI_PROJECT_DIR/terraform-plan-${TF_STATE_NAME}.tfplan.json
  resource_group: ${TF_STATE_NAME}
  artifacts:
    expire_in: 60 mins
    paths:
      - "terraform-plan-*.tfplan"
      - "terraform-plan-*.tfplan.json"

####################
# static analysis stage jobs
####################

.tfsec:
  image: aquasec/tfsec-ci:${TFSEC_VERSION}
  stage: static-analysis
  script:
    - cd "${TF_ROOT}"
    - tfsec --version
    - tfsec .

####################
# apply stage jobs
####################

.terraform:apply:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://cicd.skyway.porsche.com
  before_script:
    - *install-requirements
    - *aws-oidc-login
    - *git-config
    - *setup-variables
    - echo "Terraform variables set to ${TF_VARS}"
    - *terraform-init
  script:
    - terraform apply -auto-approve "$CI_PROJECT_DIR/terraform-plan-${TF_STATE_NAME}.tfplan"
    - terraform output -json > "$CI_PROJECT_DIR/$CI_JOB_NAME.jsonoutputs"
  resource_group: ${TF_STATE_NAME}
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/*.jsonoutputs"
    expire_in: 1 hour



.terraform:destroy:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://cicd.skyway.porsche.com
  before_script:
    - *install-requirements
    - *aws-oidc-login
    - *git-config
    - *setup-variables
    - echo "Terraform variables set to ${TF_VARS}"
    - *terraform-init
  script:
    - terraform destroy -auto-approve
  resource_group: ${TF_STATE_NAME}
  when: manual # This setting turns a job into a manual one